### ISSUE TITLE
Loopback 4

### ISSUE THREAD

**Issue by karianpour** [darthwesker/react-admin-loopback#1]
Is there any plan to support loopback 4? I am interested to contribute if there is not project jet.

**Comment by darthwesker** [comment]
Hi @karianpour 

No plan yet. All contributions are welcome.

**Comment by afilp** [comment]
Hi @darthwesker,

I would also like to use loopback 4, I hope you will get the contributions you need (unfortunately I can't). If you have any plans let us know, thanks a lot!

**Comment by VinayaSathyanarayana** [comment]
Any progress/updates on this?

**Comment by afilp** [comment]
@karianpour  Could you contribute on this if you have the time? Thanks a lot!

**Comment by karianpour** [comment]
@afilp I have time. @darthwesker  tell me how should we create do it, loopback4 is not compatible with loopback3. Should I make PR to support both? Or we make a different repo for loopback4?

**Comment by darthwesker** [comment]
Hi @karianpour.
I think is better to create a different repo, something like react-admin-loopback4.
Unfortunately I don't have time to do that, but I will try to contribute.

**Comment by karianpour** [comment]
I investigated and checked the Loopback4, actually there is no way that make sense to create a general data and auth provider for react-admin, as Loopback4 is pretty flexible in many ways.
My suggestion is to create specific data and auth provider for any one one who want to use loop back 4.
Beside, loop back 4 is just assembly of some libraries, and a code generator. Personally I do not like to use it. I rather prefer to assemble my own libraries if I want to be supper flexible.

Meanwhile if some one need to connect react-admin to Loopback4, just create a copy of this repo src directory to your own react-admin repo and debug the it. As Loopback4 does not support `content-range` by default, I suggest that we ignore it and return `Number.POSITIVE_INFINITY` as the `total` property and printing a warning rather throwing an error.

The other problem is identifier. React-Admin need and `id` key for each resource. If your resources uses other key, read the [FAQ](https://marmelab.com/react-admin/FAQ.html)
