### ISSUE TITLE
GET_MANY fetch ALL data

### ISSUE THREAD

**Issue by sghribi** [darthwesker/react-admin-loopback#2]
In `index.js`, `GET_MANY` action is performed like this :

```
      case GET_MANY: {
        const query = {
          filter: JSON.stringify({ id: params.ids }),
        };
        url = `${apiUrl}/${resource}?${stringify(query)}`;
        break;
      }
```

I think it should be like this (https://github.com/kimkha/aor-loopback/blob/master/src/index.js#L55) :

```
            case GET_MANY: {
                const listId = params.ids.map(id => {
                    return {'id': id};
                });
                const query = {
                    'where': {'or': listId}
                };
                url = `${apiUrl}/${resource}?${queryParameters({filter: JSON.stringify(query)})}`;
                break;
            }
```

According to [loopback documentation](https://loopback.io/doc/en/lb3/Where-filter.html#and-and-or-operators), the request is not correct : in the first case, ALL data are fetched (this is not normal), whereas is the second case, only selected data are fetched (that's what we want).

Does anyone agree? (I can make a PR to fix this)

**Comment by darthwesker** [comment]
Hi @sghribi 

You are right.
Could you please make a PR?

Thanks

**Comment by sghribi** [comment]
Hi @darthwesker, done :)
