### ISSUE TITLE
Include auth Token

### ISSUE THREAD

**Issue by psydone** [darthwesker/react-admin-loopback#5]
If using loopback with ACLs how would you pass the localStorage session Token I can see the fetch.js trying but how is this invoked??

**Comment by psydone** [comment]
I can see now and for others:
authorisation headers are set as the accessToken id. If using loopback somehow you'll need to accept/use the header with middleware

**Comment by psydone** [comment]
Update fixed
by altering two files achieved a workaround probably ugly but FYI for those trying:
edit:
-----
...path to module/lib/fetch.js
    options.user = {
        authenticated: true,
        token: JSON.parse(localStorage.getItem('lbtoken')).id
------
and loopback
./server/server.js
  app.use(loopback.token({  
    cookies: ['access_token'],
    headers: ['access_token', 'X-Access-Token'],
    params:  ['access_token']
    //additional keys (check docs for more info)
  }));
--------
Seemed to resolve issue, mind you I don't understand why setting the 'authorisation' header as the access_token direct string while server is looking for it in access_token seems to work but feels wrong

**Comment by darthwesker** [comment]
This is confusing...
You simply ignored the "storage.js" file and you are ignoring the Expiration Date.

**Comment by psydone** [comment]
storage and storage2 I ignored because neither seem to pull the correct expiration data. my token has 'created' and 'ttl'. created being the UTC time entry and ttl the second validity. Perhaps I'm using an old version of loopback or a different way of issueing the access token on my server side but the storage.js wasn't validating the right expiration data from localstorage.
