### ISSUE TITLE
GET_MANY

### ISSUE THREAD

**Issue by afilp** [darthwesker/react-admin-loopback#8]
I have the following filter in react-admin:

```
<ReferenceArrayInput
        label="Departments"
        source="dept_id"
        reference="departments"
        allowEmpty
        perPage={1000}
        sort={{field: 'name', order: 'ASC'}}
        alwaysOn
        style={{
          minWidth: 150,
        }}
        filterToQuery={searchText => ({
          name: {
            "like": `.*${escapeRegExp(searchText)}.*`,
            "options": "i"
          }
        })}
      >
        <AutocompleteArrayInput />
      </ReferenceArrayInput>
```

When I choose a value and then remove it from the ArrayInput, I get the following error:

```Unhandled error for request GET /api/departments?filter=%7B%22where%22%3A%7B%22or%22%3A%5B%5D%7D%7D: MongoError: $and/$or/$nor must be a nonempty array```

This is because the `or` below has an **empty** array (`listId` is `[]`):

```
      case GET_MANY: {
        const listId = params.ids.map(id => {
          return {id};
        });
        const query = {
          where: {or: listId},
        };
        url = `${apiUrl}/${resource}?${stringify({filter: JSON.stringify(query)})}`;
        break;
      }
```

I think this is a bug and needs to be addressed?

**Comment by darthwesker** [comment]
Hi @afilp 

Sorry for the late reply. 
I think this error will only occur if you use MongoDB. I don't have this problem with PostgreSQL.
I created a new branch so that you can validate if this change fixed the error you are getting.

Waiting your feedback to merge the changes.

**Comment by darthwesker** [comment]
@afilp 
Could you please validate the issue #9? 
Changes in the same branch.

**Comment by afilp** [comment]
@darthwesker Thanks! My colleague confirmed that it worked.
